name: Build & Deploy Backend to Render

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'Dockerfile'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Render
        uses: render-actions/render-deploy@v1
        with:
          api_key: ${{ secrets.RENDER_API_KEY }}
          service_id: ${{ secrets.RENDER_SERVICE_ID_BACKEND }}
